 # 1.import neccessary libraries

In [ ]:
import numpy as np
import pandas as pd

In [2]:
data_set = pd.read_json("politifact_factcheck_data.json",lines=True)

In [3]:
data_set

verdict statement_originator  \
0              true         Barack Obama   
1             false           Matt Gaetz   
2       mostly-true         Kelly Ayotte   
3             false             Bloggers   
4         half-true         Bobby Jindal   
...             ...                  ...   
21147  mostly-false         Donald Trump   
21148         false     Donald Trump Jr.   
21149  mostly-false          Chris Abele   
21150         false             Bloggers   
21151  mostly-false       Facebook posts   

                                               statement statement_date  \
0      John McCain opposed bankruptcy protections for...      6/11/2008   
1      "Bennie Thompson actively cheer-led riots in t...       6/7/2022   
2      Says Maggie Hassan was "out of state on 30 day...      5/18/2016   
3      "BUSTED: CDC Inflated COVID Numbers, Accused o...       2/1/2021   
4      "I'm the only (Republican) candidate that has ...      8/30/2015   
...                                                  ...            ...   
21147  Says the large trade deficit with Japan stems ...      8/13/2019   
21148  "Tens of thousands" of people leave New York e...      11/1/2019   
21149  "I have fought for our shared values without b...       1/4/2011   
21150  "Germany halts all Covid-19 vaccines, says the...      8/27/2021   
21151  Says for otherwise healthy people "experiencin...      3/28/2020   

      statement_source         factchecker factcheck_date  \
0               speech   Adriel Bettelheim      6/16/2008   
1           television         Yacob Reyes      6/13/2022   
2                 news      Clay Wirestone      5/27/2016   
3                 blog      Madison Czopek       2/5/2021   
4           television           Linda Qiu      8/30/2015   
...                ...                 ...            ...   
21147           speech       Jon Greenberg      8/15/2019   
21148     social_media  Jill Terreri Ramos      11/8/2019   
21149             news       Dave Umhoefer      1/13/2011   
21150             blog      Ciara O'Rourke       9/9/2021   
21151     social_media       Tom Kertscher       4/3/2020   

                                 factcheck_analysis_link  
0      https://www.politifact.com/factchecks/2008/jun...  
1      https://www.politifact.com/factchecks/2022/jun...  
2      https://www.politifact.com/factchecks/2016/may...  
3      https://www.politifact.com/factchecks/2021/feb...  
4      https://www.politifact.com/factchecks/2015/aug...  
...                                                  ...  
21147  https://www.politifact.com/factchecks/2019/aug...  
21148  https://www.politifact.com/factchecks/2019/nov...  
21149  https://www.politifact.com/factchecks/2011/jan...  
21150  https://www.politifact.com/factchecks/2021/sep...  
21151  https://www.politifact.com/factchecks/2020/apr...  

[21152 rows x 8 columns]

In [4]:
data_set1=data_set.iloc[:,0]

In [5]:
data_set1

0                true
1               false
2         mostly-true
3               false
4           half-true
             ...     
21147    mostly-false
21148           false
21149    mostly-false
21150           false
21151    mostly-false
Name: verdict, Length: 21152, dtype: object

In [6]:
data_set2=data_set.iloc[:,2]

In [7]:
data_set2

0        John McCain opposed bankruptcy protections for...
1        "Bennie Thompson actively cheer-led riots in t...
2        Says Maggie Hassan was "out of state on 30 day...
3        "BUSTED: CDC Inflated COVID Numbers, Accused o...
4        "I'm the only (Republican) candidate that has ...
                               ...                        
21147    Says the large trade deficit with Japan stems ...
21148    "Tens of thousands" of people leave New York e...
21149    "I have fought for our shared values without b...
21150    "Germany halts all Covid-19 vaccines, says the...
21151    Says for otherwise healthy people "experiencin...
Name: statement, Length: 21152, dtype: object

In [8]:
df=pd.concat([data_set1,data_set2],axis=1)

In [9]:
df

verdict                                          statement
0              true  John McCain opposed bankruptcy protections for...
1             false  "Bennie Thompson actively cheer-led riots in t...
2       mostly-true  Says Maggie Hassan was "out of state on 30 day...
3             false  "BUSTED: CDC Inflated COVID Numbers, Accused o...
4         half-true  "I'm the only (Republican) candidate that has ...
...             ...                                                ...
21147  mostly-false  Says the large trade deficit with Japan stems ...
21148         false  "Tens of thousands" of people leave New York e...
21149  mostly-false  "I have fought for our shared values without b...
21150         false  "Germany halts all Covid-19 vaccines, says the...
21151  mostly-false  Says for otherwise healthy people "experiencin...

[21152 rows x 2 columns]

In [10]:
print(list(df.columns))

['verdict', 'statement']


# import nlp based libraries

In [11]:
import nltk
import re
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\deepa\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [12]:
from nltk.stem.porter import PorterStemmer
from nltk.corpus import  stopwords

In [13]:
statement=df['statement'][0]

In [14]:
statement

'John McCain opposed bankruptcy protections for families "who were only in bankruptcy because of medical expenses they couldn\'t pay."'

In [15]:
statement=re.sub('[^a-zA-Z]',' ',statement)

In [16]:
statement

'John McCain opposed bankruptcy protections for families  who were only in bankruptcy because of medical expenses they couldn t pay  '

In [17]:
statement = statement.lower()
statement

'john mccain opposed bankruptcy protections for families  who were only in bankruptcy because of medical expenses they couldn t pay  '

In [18]:
statement=statement.split()
statement

['john',
 'mccain',
 'opposed',
 'bankruptcy',
 'protections',
 'for',
 'families',
 'who',
 'were',
 'only',
 'in',
 'bankruptcy',
 'because',
 'of',
 'medical',
 'expenses',
 'they',
 'couldn',
 't',
 'pay']

In [19]:
ps=PorterStemmer()
statement=[ps.stem(word) for word in statement if not  word in set(stopwords.words('english'))]
statement

['john',
 'mccain',
 'oppos',
 'bankruptci',
 'protect',
 'famili',
 'bankruptci',
 'medic',
 'expens',
 'pay']

In [20]:
x=stopwords.words('english')

In [21]:
x

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [22]:
data=[]
for i in range(0,21152):

    review=df['statement'][i]
#a)remove un neccessary .,
    review=re.sub('[^a-zA-Z]',' ',review)
#b) lower case the text
    review=review.lower()
#c)split the text
    review=review.split()
#4.stemming
#5. remove stop words
    ps=PorterStemmer()
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
#6.join the splitted data
    review=' '.join(review)
    data.append(review)

In [24]:
data

['john mccain oppos bankruptci protect famili bankruptci medic expens pay',
 'benni thompson activ cheer led riot',
 'say maggi hassan state day last three month',
 'bust cdc inflat covid number accus violat feder law',
 'republican candid actual reduc size govern',
 'actual countri practic birthright citizenship',
 'husband never gotten penni money farm',
 'go strictli number crime across board last year percent decreas seriou crime',
 'american peopl say touch social secur touch medicar cut defens percent feder budget',
 'sinc ceo compens rose averag worker',
 'say accomplish includ fiscal respons budget agreement control state spend',
 'say presid obama deal allow iran produc nuclear weapon',
 'say donald trump say climat chang hoax invent chines',
 'least ballot key state miracul mark joe biden candid',
 'percent american adult commit crime could lead imprison',
 'say stimulu bill sent tax credit oversea billion solar compani build plant mexico',
 'tampa bay lead state job creation

#7.vectorization text to numerical format



In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
tf=TfidfVectorizer(max_features=20000)

In [29]:
x=tf.fit_transform(data).toarray()
y=df.iloc[:,0]

In [30]:
y

0                true
1               false
2         mostly-true
3               false
4           half-true
             ...     
21147    mostly-false
21148           false
21149    mostly-false
21150           false
21151    mostly-false
Name: verdict, Length: 21152, dtype: object

In [31]:
x.shape

(21152, 11009)

In [32]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1000)

In [34]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(16921, 11009)
(4231, 11009)
(16921,)
(4231,)


In [35]:
y_train

1336     mostly-false
14224           false
4743     mostly-false
16558       half-true
1449     mostly-false
             ...     
15611       half-true
3776            false
6215            false
4695            false
9651            false
Name: verdict, Length: 16921, dtype: object

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

logreg = LogisticRegression(solver='lbfgs',max_iter=1000)

# Train the model using the training sets and check score
logreg.fit(X_train, y_train)

# Predict Output
log_predicted= logreg.predict(X_test)

logreg_score = round(logreg.score(X_train, y_train) * 100, 2)
logreg_score_test = round(logreg.score(X_test, y_test) * 100, 2)

# Equation coefficient and Intercept
print('Logistic Regression Training Score: \n', logreg_score)
print('Logistic Regression Test Score: \n', logreg_score_test)

print('Accuracy: \n', round(accuracy_score(y_test,log_predicted)*100,2))
print('Confusion Matrix: \n', confusion_matrix(y_test,log_predicted))
print('Classification Report: \n', classification_report(y_test,log_predicted))

Logistic Regression Training Score: 
 55.5
Logistic Regression Test Score: 
 29.12
Accuracy: 
 29.12
Confusion Matrix: 
 [[640 126  93  91  89  33]
 [274 150 107 130  19  33]
 [302 136 103  94  36  25]
 [214 149  74 178  11  58]
 [333  34  45  23  99   7]
 [167 101  50 130  15  62]]
Classification Report: 
               precision    recall  f1-score   support

       false       0.33      0.60      0.43      1072
   half-true       0.22      0.21      0.21       713
mostly-false       0.22      0.15      0.18       696
 mostly-true       0.28      0.26      0.27       684
  pants-fire       0.37      0.18      0.24       541
        true       0.28      0.12      0.17       525

    accuracy                           0.29      4231
   macro avg       0.28      0.25      0.25      4231
weighted avg       0.28      0.29      0.27      4231



In [38]:
from sklearn.naive_bayes import MultinomialNB
mn = MultinomialNB()
mn.fit(X_train, y_train)
# Predict Output
mn_predicted = mn.predict(X_test)

mn_score = round(mn.score(X_train, y_train) * 100, 2)
mn_score_test = round(mn.score(X_test, y_test) * 100, 2)
print('Multinomial Score: \n', mn_score)
print('Multinomial Test Score: \n', mn_score_test)

print('Accuracy: \n', round(accuracy_score(y_test, mn_predicted)*100,2))
print(confusion_matrix(y_test,mn_predicted))
print(classification_report(y_test,mn_predicted))

Multinomial Score: 
 44.39
Multinomial Test Score: 
 28.69
Accuracy: 
 28.69
[[869 106  32  50  13   2]
 [423 166  35  87   2   0]
 [486 136  31  41   2   0]
 [389 143  24 127   0   1]
 [460  36  16   9  19   1]
 [317  86  14 106   0   2]]
              precision    recall  f1-score   support

       false       0.30      0.81      0.43      1072
   half-true       0.25      0.23      0.24       713
mostly-false       0.20      0.04      0.07       696
 mostly-true       0.30      0.19      0.23       684
  pants-fire       0.53      0.04      0.07       541
        true       0.33      0.00      0.01       525

    accuracy                           0.29      4231
   macro avg       0.32      0.22      0.17      4231
weighted avg       0.31      0.29      0.21      4231



In [39]:
from sklearn.svm import SVC,LinearSVC

In [ ]:
from sklearn.svm import SVC,LinearSVC
svm_model = SVC(kernel='linear')
svm_model.fit(X_train, y_train)
svm_model_score = round(svm_model.score(X_train, y_train) * 100, 2)
svm_model_score_test = round(svm_model.score(X_test, y_test) * 100, 2)

print('svm_model_score: \n', svm_model_score)
print('svm_model_score_test: \n', svm_model_score_test)

Y_predict = svm_model.predict(X_test)
svm_accuracy = accuracy_score(y_test,Y_predict)*100
print("Accuracy:",svm_accuracy)
cm = confusion_matrix(y_test,Y_predict)
print("Confusion Matrix is :", cm)
print(classification_report(y_test,Y_predict))

In [ ]:
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, y_train)
# Predict Output   
rf_predicted = random_forest.predict(X_test)

random_forest_score = round(random_forest.score(X_train, y_train) * 100, 2)
random_forest_score_test = round(random_forest.score(X_test, y_test) * 100, 2)
print('Random Forest Score: \n', random_forest_score)
print('Random Forest Test Score: \n', random_forest_score_test)
print('Accuracy: \n', accuracy_score(y_test,rf_predicted))
print(confusion_matrix(y_test,rf_predicted))
print(classification_report(y_test,rf_predicted))

In [ ]:
from sklearn.model_selection import GridSearchCV, train_test_split, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

params = {
    "n_neighbors":[3,5,7,9],
    "weights":["uniform","distance"],
    "algorithm":["ball_tree","kd_tree","brute"],
    "leaf_size":[25,30,35],
    "p":[1,2]
}

gs = GridSearchCV(knn, param_grid=params)
knn_model = gs.fit(X_train,y_train)

knn_model_score = round(knn_model.score(X_train, y_train) * 100, 2)
Y_predict = knn_model.predict(X_test)
knn_accuracy = accuracy_score(y_test,Y_predict)*100
print("Accuracy:",knn_accuracy)
cm = confusion_matrix(y_test,Y_predict)
print("Confusion Matrix is :", cm)

In [ ]:
#Comparing all the models
models = pd.DataFrame({
    'Model': [ 'Logistic Regression', 'Gaussian Naive Bayes','Random Forest','SVM Model', "KNN"],
    'Score': [ logreg_score, gauss_score, random_forest_score,svm_model_score,knn_model_score],
    'Test Score': [ logreg_score_test, gauss_score_test, random_forest_score_test,svm_accuracy,knn_accuracy]})
models.sort_values(by='Test Score', ascending=False)